// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxQaIZ2ZHnLJZzKq_XywEqUAgDKSCSQUc',
    appId: '1:123007460890:web:a41a9e4c320a8c209e93a3',
    messagingSenderId: '123007460890',
    projectId: 'crwn-db-84a39',
    authDomain: 'crwn-db-84a39.firebaseapp.com',
    databaseURL: 'https://crwn-db-84a39.firebaseio.com',
    storageBucket: 'crwn-db-84a39.appspot.com',
    measurementId: 'G-W7HEQV4J8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk_NdO4QTLI87L_n3tdsQwZnkh9oW_fDQ',
    appId: '1:123007460890:android:bd68e46da9e6ad649e93a3',
    messagingSenderId: '123007460890',
    projectId: 'crwn-db-84a39',
    databaseURL: 'https://crwn-db-84a39.firebaseio.com',
    storageBucket: 'crwn-db-84a39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHAW7nPljaZUicRi7alK_f2QNN421n97k',
    appId: '1:123007460890:ios:f8b5c8c57d5eac019e93a3',
    messagingSenderId: '123007460890',
    projectId: 'crwn-db-84a39',
    databaseURL: 'https://crwn-db-84a39.firebaseio.com',
    storageBucket: 'crwn-db-84a39.appspot.com',
    iosClientId: '123007460890-t3vm44u29paq0qkjhar4b8nmlf2a4t90.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHAW7nPljaZUicRi7alK_f2QNN421n97k',
    appId: '1:123007460890:ios:f8b5c8c57d5eac019e93a3',
    messagingSenderId: '123007460890',
    projectId: 'crwn-db-84a39',
    databaseURL: 'https://crwn-db-84a39.firebaseio.com',
    storageBucket: 'crwn-db-84a39.appspot.com',
    iosClientId: '123007460890-t3vm44u29paq0qkjhar4b8nmlf2a4t90.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
